name: Example
on: push
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - name: blah
      run: |
        mkdir blah
        cd blah
        touch gnargh
    - name: another
      run: |
        ls
