name: End-to-end tests
on: [push, pull_request]

env:
  DEBIAN_FRONTEND: noninteractive
  LIBRAFT_TRACE: 1
  LIBDQLITE_TRACE: 1

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/canonical/raft
          git clone https://github.com/canonical/dqlite
          git clone https://github.com/canonical/go-dqlite
          git clone https://github.com/canonical/jepsen.dqlite
      - name: Install dependencies
        run: |
          sudo apt-get install \
            gcc \
            gnuplot \
            graphviz \
            leiningen \
            libjna-java \
            liblz4-dev \
            libsqlite3-dev \
            libuv1-dev
          sudo snap install go --classic
      - name: Build and install raft
        run: |
          cd raft
          gcc -shared -fPIC -g3 -DLZ4_AVAILABLE -DLZ4_ENABLED -DHAVE_LINUX_AIO_ABI_H src/*.c -o libraft.so
          sudo install -m644 libraft.so /usr/lib
          ls -l /usr/lib/libraft.so
      - name: Build and install dqlite
        run: 'true'
      - name: Run dqlite tests
        run: 'true'
      - name: Build and install go-dqlite
        run: 'true'
      - name: Run go-dqlite tests
        run: 'true'
      - name: Run Jepsen tests
        run: 'true'
