name: End-to-end tests
on: [push, pull_request]

env:
  DEBIAN_FRONTEND: noninteractive
  LIBRAFT_TRACE: 1
  LIBDQLITE_TRACE: 1

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        run: |
          git clone --depth 1 https://github.com/canonical/raft
          git clone --depth 1 https://github.com/canonical/dqlite
          git clone --depth 1 https://github.com/canonical/go-dqlite
          git clone --depth 1 https://github.com/canonical/jepsen.dqlite
      - name: Install apt dependencies
        run: |
          sudo apt update
          sudo apt-get install \
            gcc \
            gnuplot \
            graphviz \
            leiningen \
            libjna-java \
            liblz4-dev \
            libsqlite3-dev \
            libuv1-dev
      - name: Install Go toolchain
        uses: actions/setup-go@v3
      - name: Check raft
        if: ${{ inputs.check-raft }}
        run: |
          cd raft
          autoreconf -i
          ./configure --enable-debug --enable-uv
          make -j$(nproc) check
      - name: Install raft (fast)
        run: |
          shopt -s globstar
          cd raft
          gcc -shared -fPIC -g3 -D_GNU_SOURCE -DLZ4_AVAILABLE -DLZ4_ENABLED -DHAVE_LINUX_AIO_ABI_H src/**/*.c -o libraft.so -luv -llz4
          sudo install -m644 include/raft.h /usr/include
          sudo install -d /usr/include/raft
          sudo install -m644 include/raft/uv.h /usr/include/raft
          sudo install -m644 libraft.so /usr/lib
        shell: bash
      - name: Check dqlite
        if: ${{ inputs.check-dqlite }}
        run: |
          cd dqlite
          autoreconf -i
          ./configure --enable-debug
          make -j$(nproc) check
      - name: Install dqlite (fast)
        run: |
          shopt -s globstar
          cd dqlite
          gcc -shared -fPIC -g3 -D_GNU_SOURCE src/**/*.c -o libdqlite.so -lsqlite3 -lraft
          sudo install -m644 include/dqlite.h /usr/include
          sudo install -m644 libdqlite.so /usr/lib
        shell: bash
      - name: Check go-dqlite
        if: ${{ inputs.check-go-dqlite }}
        run: |
          cd go-dqlite
          go test -tags nosqlite3 ./...
      - name: Prepare for Jepsen
        run: |
          printf core | sudo tee /proc/sys/kernel/core_pattern
      - name: Run Jepsen tests
        run: |
          cd jepsen.dqlite
          go get golang.org/x/sync/semaphore
          echo 'replace github.com/canonical/go-dqlite => ../go-dqlite' >>go.mod
          go build -tags nosqlite3 -o resources/app resources/app.go
          sudo ufw disable
          sleep 0.2
          sudo systemctl stop ufw
          sudo ./resources/network.sh setup 5
          lein run test --no-ssh --binary $(pwd)/resources/app \
            --workload append \
            --nemesis stop \
            --rate 100 \
            --time-limit 240 \
            --disk 0
          sudo ./resources/network.sh teardown 5

